name: Create merge PR

on:
  push:
    branches:
    - 'main*'

jobs:
  create-merge:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # this step should be different for different branches to create appropriate PRs.
      # e.g. main > main2, main2 > main3m, etc.
      - id: create_pr
        name: Create PR to main2
        if: ${{ github.ref_name == 'main' }}
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'main2'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # label must be same that is used in automerge step
          pr_label: "auto-pr"

      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v2.0.0
        with:
          # we have to use token other than that was used to create this PR
          github-token: ${{ secrets.PAT }}
          number: ${{ steps.create_pr.outputs.pr_number }}

      - id: automerge
        name: automerge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PULL_REQUEST: ${{ steps.create_pr.outputs.pr_number }}
          # it seems unnecessary if number is provided, but we'll keep it
          MERGE_LABELS: "auto-pr"

      # if automerge failed to merge, it still results with success
      - name: Check automerge result
        # if: ${{ steps.automerge.outputs.mergeResult != 'merged' }}
        if: ${{ steps.automerge.outputs.mergeResult == 'not_ready' || steps.automerge.outputs.mergeResult == 'merge_failed' }}
        shell: bash
        run: |
          echo "Pull request was not merged!"
          exit 1

